package io.cresco.cpms.statics;

public class TestStatics {
    public static final String PIPELINE_NAME = "testPipeline";
    public static final String PIPELINE_SCRIPT = String.join(System.getProperty("line.separator"),
            "{",
            "   \"tasks\": [",
            "       {",
            "           \"name\": \"testTask\",",
            "           \"script\": {",
            "               \"commands\": [",
            "                   {",
            "                       \"name\": \"Download input files from S3 archive\",",
            "                       \"method\": \"download-s3-archive\",",
            "                       \"parameters\": {",
            "                           \"host\": \"s3.amazonaws.com\",",
            "                           \"bucket\": \"cpms-test-bucket\",",
            "                           \"destination\": $input",
            "                       }",
            "                   },",
            "                   {",
            "                       \"name\": \"Run Docker container\",",
            "                       \"method\": \"run-docker-container\",",
            "                       \"parameters\": {",
            "                           \"image\": \"hello-world\",",
            "                           \"volumes\": {",
            "                               \"/gdata/input\": $input,",
            "                               \"/gdata/output\": $output",
            "                           },",
            "                           \"command\": \"ls /gdata/input\"",
            "                       }",
            "                   },",
            "                   {",
            "                       \"name\": \"Upload result files to s3 archive\",",
            "                       \"method\": \"upload-s3-archive\",",
            "                       \"parameters\": {",
            "                           \"host\": \"s3.amazonaws.com\",",
            "                           \"bucket\": \"cpms-test-bucket\",",
            "                           \"source\": $output",
            "                       }",
            "                   }",
            "               ]",
            "           }",
            "       }",
            "   ]",
            "}"
    );
}
